# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # Define your GoogleAuthenticator service
    App\Security\GoogleAuthenticator:
        arguments:
            $clientRegistry: '@KnpU\OAuth2ClientBundle\Client\ClientRegistry'
            $em: '@Doctrine\ORM\EntityManagerInterface'
            $router: '@Symfony\Component\Routing\RouterInterface'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
    Dompdf\Dompdf:
        arguments:
            $options: '@Dompdf\Options'
    # Define a service for Dompdf\Options
    Dompdf\Options:
        class: Dompdf\Options
    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
